# Generated by Django 5.1 on 2024-09-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_description_task_add_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='add_notes',
            field=models.TextField(blank=True),
        ),
    ]
